# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php81-apache
    ports:
      -  127.0.0.9:80:80
    volumes:
      - ./..:/var/www/html/
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data-rbl:/var/lib/mysql
    ports:
      - 3309:3306
volumes:
  mysql-data-rbl:
